export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
    GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
    GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",

    CREAT_PRODUCT_REQUEST: 'CREAT_PRODUCT_REQUEST',
    CREAT_PRODUCT_SUCCESS: 'CREAT_PRODUCT_SUCCESS',
    CREAT_PRODUCT_FAILURE: 'CREAT_PRODUCT_FAILURE',

    UPLOAD_PICTURE_REQUEST: 'UPLOAD_PICTURE_REQUEST',
    UPLOAD_PICTURE_SUCCESS: 'UPLOAD_PICTURE_SUCCESS',
    UPLOAD_PICTURE_FAILURE: 'UPLOAD_PICTURE_FAILURE',

    DESTROY_PICTURE_REQUEST: "DESTROY_PICTURE_REQUEST",
    DESTROY_PICTURE_SUCCESS: "DESTROY_PICTURE_SUCCESS",
    DESTROY_PICTURE_FAILURE: "DESTROY_PICTURE_FAILURE",

    UPDATE_PRODUCTS_REQUEST: "UPDATE_PRODUCTS_REQUEST",
    UPDATE_PRODUCTS_SUCCESS: "UPDATE_PRODUCTS_SUCCESS",
    UPDATE_PRODUCTS_FAILURE: "UPDATE_PRODUCTS_FAILURE",

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAIILURE: 'DELETE_PRODUCT_FAIILURE',

    DELETE_PRODUCTS_REQUEST: 'DELETE_PRODUCTS_REQUEST',
    DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',
    DELETE_PRODUCTS_FAIILURE: 'DELETE_PRODUCTS_FAIILURE',
}

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    KEEP_USER_LOGIN_SUCCESS: 'KEEP_USER_LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    USER_INFOR_SUCCESS: 'USER_INFOR_SUCCESS',
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    show_toast_success: 'show_toast_success'
}


export const cartConstants = {
    CART_INCREMENT_REQUEST: "CART_INCREMENT_REQUEST",
    CART_INCREMENT_SUCCESS: "CART_INCREMENT_SUCCESS",
    CART_INCREMENT_FAILURE: "CART_INCREMENT_FAILURE",
    CART_DECREMENT_REQUEST: "CART_DECREMENT_REQUEST",
    CART_DECREMENT_SUCCESS: "CART_DECREMENT_SUCCESS",
    CART_DECREMENT_FAILURE: "CART_DECREMENT_FAILURE",
    CART_REMOVE_REQUEST: "CART_REMOVE_REQUEST",
    CART_REMOVE_SUCCESS: "CART_REMOVE_SUCCESS",
    CART_REMOVE_FAILURE: "CART_REMOVE_FAILURE",
}
export const paymentConstants = {
    GET_HISTORY_PAYMENTS_REQUEST: 'GET_HISTORY_PAYMENTS_REQUEST',
    GET_HISTORY_PAYMENTS_SUCCESS: 'GET_HISTORY_PAYMENTS_SUCCESS',
    GET_HISTORY_PAYMENTS_FAILURE: 'GET_HISTORY_PAYMENTS_FAILURE',
}


export const catagoryConstants = {
    GET_CATAGORIES_REQUEST: "GET_CATAGORIES_REQUEST",
    GET_CATAGORIES_SUCCESS: "GET_CATAGORIES_SUCCESS",
    GET_CATAGORIES_FAILURE: "GET_CATAGORIES_FAILURE",
    CREATE_CATAGORY_REQUEST: 'CREATE_CATAGORY_REQUEST',
    CREATE_CATAGORY_SUCCESS: 'CREATE_CATAGORY_SUCCESS',
    CREATE_CATAGORY_FAILURE: 'CREATE_CATAGORY_FAILURE',
}


export const filteringConstants = {
    UPDATE_SEARCH_SUCCESS: 'UPDATE_SEARCH_SUCCESS',
    UPDATE_PAGE_SUCCESS: 'UPDATE_PAGE_SUCCESS',
    UPDATE_CATAGORY_SUCCESS: 'UPDATE_CATAGORY_SUCCESS',
    UPDATE_SORT_SUCCESS: 'UPDATE_SORT_SUCCESS',
    UPDATE_RESULT_SUCCESS: 'UPDATE_RESULT_SUCCESS',
    UPDATE_TOTALPAGES_SUCCESS: 'UPDATE_TOTALPAGES_SUCCESS',
}
